theme: jekyll-theme-minimal
title: docs for my folks
logo: https://avatars.githubusercontent.com/u/968593?s=200

how_to_make_this_monster_up_and_running: https://mesmerze.github.io/pages_demo/how_to_make_this_monster_up_and_running
