theme: jekyll-theme-minimal
title: docs for my folks
logo: https://avatars.githubusercontent.com/u/968593?s=200

how_to_run_this_monster_url: https://mesmerze.github.io/pages_demo/how_to_run_this_monster
